dbUser: root
dbPassword: 
dbHost: 127.0.0.1
dbPort: 3306
dbDatabase: im
redisAddr: 127.0.0.1:6379
redisPassWord:
routeServerAddr: :3333
logDir: log/
logExpire: 168
rotationFormat: Day
rotationTime: 24