// Code generated by protoc-gen-go. DO NOT EDIT.
// source: route.proto

/*
Package mp is a generated protocol buffer package.

It is generated from these files:
	route.proto

It has these top-level messages:
	RouteLoginIm
	RouteLogoutIm
	RouteMsgIm
*/
package mp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "im/mp/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RouteLoginIm struct {
	AppId  int32 `protobuf:"varint,1,opt,name=AppId" json:"AppId,omitempty"`
	UserId int64 `protobuf:"varint,2,opt,name=UserId" json:"UserId,omitempty"`
}

func (m *RouteLoginIm) Reset()                    { *m = RouteLoginIm{} }
func (m *RouteLoginIm) String() string            { return proto.CompactTextString(m) }
func (*RouteLoginIm) ProtoMessage()               {}
func (*RouteLoginIm) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RouteLoginIm) GetAppId() int32 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *RouteLoginIm) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type RouteLogoutIm struct {
	AppId  int32 `protobuf:"varint,1,opt,name=AppId" json:"AppId,omitempty"`
	UserId int64 `protobuf:"varint,2,opt,name=UserId" json:"UserId,omitempty"`
}

func (m *RouteLogoutIm) Reset()                    { *m = RouteLogoutIm{} }
func (m *RouteLogoutIm) String() string            { return proto.CompactTextString(m) }
func (*RouteLogoutIm) ProtoMessage()               {}
func (*RouteLogoutIm) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RouteLogoutIm) GetAppId() int32 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *RouteLogoutIm) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type RouteMsgIm struct {
	AppId         int32         `protobuf:"varint,1,opt,name=AppId" json:"AppId,omitempty"`
	SenderId      int64         `protobuf:"varint,2,opt,name=SenderId" json:"SenderId,omitempty"`
	ReceiverId    int64         `protobuf:"varint,3,opt,name=ReceiverId" json:"ReceiverId,omitempty"`
	TransportData *common.MsgIm `protobuf:"bytes,4,opt,name=TransportData" json:"TransportData,omitempty"`
}

func (m *RouteMsgIm) Reset()                    { *m = RouteMsgIm{} }
func (m *RouteMsgIm) String() string            { return proto.CompactTextString(m) }
func (*RouteMsgIm) ProtoMessage()               {}
func (*RouteMsgIm) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RouteMsgIm) GetAppId() int32 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *RouteMsgIm) GetSenderId() int64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *RouteMsgIm) GetReceiverId() int64 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *RouteMsgIm) GetTransportData() *common.MsgIm {
	if m != nil {
		return m.TransportData
	}
	return nil
}

func init() {
	proto.RegisterType((*RouteLoginIm)(nil), "mp.RouteLoginIm")
	proto.RegisterType((*RouteLogoutIm)(nil), "mp.RouteLogoutIm")
	proto.RegisterType((*RouteMsgIm)(nil), "mp.RouteMsgIm")
}

func init() { proto.RegisterFile("route.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xca, 0x2f, 0x2d,
	0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xca, 0x2d, 0x90, 0xe2, 0x49, 0xce, 0xcf,
	0xcd, 0xcd, 0xcf, 0x83, 0x88, 0x28, 0xd9, 0x70, 0xf1, 0x04, 0x81, 0x14, 0xf8, 0xe4, 0xa7, 0x67,
	0xe6, 0x79, 0xe6, 0x0a, 0x89, 0x70, 0xb1, 0x3a, 0x16, 0x14, 0x78, 0xa6, 0x48, 0x30, 0x2a, 0x30,
	0x6a, 0xb0, 0x06, 0x41, 0x38, 0x42, 0x62, 0x5c, 0x6c, 0xa1, 0xc5, 0xa9, 0x45, 0x9e, 0x29, 0x12,
	0x4c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x50, 0x9e, 0x92, 0x2d, 0x17, 0x2f, 0x4c, 0x77, 0x7e, 0x69,
	0x09, 0xc9, 0xda, 0x27, 0x33, 0x72, 0x71, 0x81, 0xf5, 0xfb, 0x16, 0xa7, 0xe3, 0xd4, 0x2c, 0xc5,
	0xc5, 0x11, 0x9c, 0x9a, 0x97, 0x82, 0xa4, 0x1d, 0xce, 0x17, 0x92, 0xe3, 0xe2, 0x0a, 0x4a, 0x4d,
	0x4e, 0xcd, 0x2c, 0x03, 0xcb, 0x32, 0x83, 0x65, 0x91, 0x44, 0x84, 0x8c, 0xb9, 0x78, 0x43, 0x8a,
	0x12, 0xf3, 0x8a, 0x0b, 0xf2, 0x8b, 0x4a, 0x5c, 0x12, 0x4b, 0x12, 0x25, 0x58, 0x14, 0x18, 0x35,
	0xb8, 0x8d, 0x78, 0xf5, 0xa0, 0x61, 0x00, 0xb6, 0x37, 0x08, 0x55, 0x4d, 0x12, 0x1b, 0x38, 0x64,
	0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x49, 0x80, 0x53, 0xcb, 0x3a, 0x01, 0x00, 0x00,
}
